name: CI

on: [push]

jobs:
  examples:
    name: Run examples
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/cache@v3
        name: Cache venv
        with:
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}

      - name: Install with dev
        run: uv sync

      - name: Run examples
        run: |
          uv run examples/pair/main.py
          uv run examples/pubsub/main.py